language: python

python:
    - "3.4"

sudo: false

service:
    - postgresql

install:
    - pip install --upgrade pip
    - pip --version
    - pip install Flask
    - pip install Flask-Script
    - pip install Flask-SQLAlchemy
    - pip install Flask-Restless
    - pip install Flask-Cors
    - pip install Flask-Testing
    - pip install requests
    - pip install psycopg2

before_script:
    - uname -a
    - printenv
    - pip list
    - psql -c 'create database travis_ci_test;' -U postgres

script:
    - date
    - ls -al
    - make check
    - make test
